### ISSUE TITLE
GDPR incompatibility 

### ISSUE THREAD

**Issue by Granitosaurus** [Minds/minds#103]
Recently in europe new law came into effect: General Data Protection Regulation (GDPR)

Unfortunately minds.com is currently not compatible with GDPR requirements (AFAIK).

Here are the TL;DR of requirements[1]:

1. the right to be forgotten, which allows EU subjects to request a controller or processor erase or cease dissemination of their personal data.
2. the right for EU subjects to request access to their personal data in a commonly used format or request that the data be shared with other data controllers.
3. new rights for EU data subjects if their personal data is used by companies that implement machine learning or if governments request that data for criminal investigations.

minds.com coverage of these requirements:

1. You can already disable account however I'm not sure if logs are being cleared sufficiently. Disable should be a complete removal of account including ip addresses in logs.
2. Currently it is not possible to export your data at all.
3. This one doesn't really apply to minds, though having a transparency page would be nice.

We can take a look at Mastodon's approach addressing this here: https://github.com/tootsuite/mastodon/issues/7280#issuecomment-385193030

[1] - http://actonline.org/2018/02/12/tl-dr-the-gdpr-is-coming-and-this-guide-will-help-you-prepare/

**Comment by DaGhostman** [comment]
***DESCLIMER** I am no lawyer and in no way I am giving a legal advise here, only am expressing my personal understanding on the subject from the perspective of a software developer*

I would have to argue with 

>  Disable should be a complete removal of account **including ip addresses in logs**.

the GDPR permits storing such kind of data, BUT there must be a short retention period, like for example not only do logs come into scope, but also backups. A Service Provider is not required to alter their backups, BUT not keep said backups indefinitely(or for too long periods of time) and if a backup is used the "forgotten" users should be removed after the restore. 

Which frankly is the case with most (decent) software companies, there is no point in having logs from 1 year, because those are too outdated to provide any benefit in storing and the same goes for backups - who would restore a backup of a Social Network from a year ago? -so backups and logs for say 1 or 2 months are aboslutely fine in terms of GDPR.
