### ISSUE TITLE
Friends & Family Content

### ISSUE THREAD

**Issue by ghost** [Minds/minds#122]
No one will leave Facebook for Minds if all their content is public. It would be great if there were some features to accommodate these users. The most common issue is `privacy` but if you leverage some of the ideas behind RSS, etc and allow users to keep their own data, perhaps you can get around that.

**Comment by denis-pujdak** [comment]
We can use private groups for that purpose. 
But without giving publicity your relatives details as it is not a good thing.

**Comment by ashtonhogan** [comment]
@denis-pujdak I was also thinking groups but then the problem is that they're not flexible enough. Think about it. Every single person has their own circle of friends and family so if you have one group, there's going to be strangers and content that's relevant to some and irrelevant to others.

I was thinking that when you post, you can already select `Public` and figured, if you could just create more scopes in this way like `High School Friends`, `Immediate Family`, `All Relatives`, etc and then post to specific audiences that could work.

The main challenge, however, is that you don't really want any private content on a Minds database. You really want to be more of a peer to peer engine, similar to RSS or my [idea](https://github.com/ashtonhogan/journodo). For example:

`Sam has a photo from the weekend and wants to share it with his immediate family so he plugs in his USB drive and makes it available via Minds. Sally logs in, notices that he is currently online and sharing private content and goes in to view and save a copy to her cache or permanent storage`.

**Comment by trymeouteh** [comment]
I agree with you. I understand a way around it is by making private groups but this is not ideal since users will have to post things many times. For example if James want to post his fishing trip pictures for his friends and family to see he would have to post it in his friends fishing group, friends soccer group, coworkers group, family group and so on.

I have made a post on minds on how to go about this. What Is needed is friend lists and walls.

https://www.minds.com/newsfeed/902785004737679360
