### ISSUE TITLE
uniting elgg programmers with the minds platform

### ISSUE THREAD

**Issue by propertunist** [Minds/minds#8]
i am not clear how much minds uses of elgg now, am i correct in thinking that the basis of minds.com is still elgg? and that when elgg releases an upgrade then minds upgrades it's elgg parts too?
i saw the post in the elgg community a few weeks ago announcing the release on github of the minds code (https://elgg.org/discussion/view/2528547/minds-just-open-sourced-a-fork-of-elgg-on-angular2-cassandra-and-more#elgg-object-2541161) and am wondering how best to approach the opening of a creative flow back into elgg from minds and thus to then also expand the flow of input into minds from the elgg community. 

for example, elgg lacks realtime notifications and minds has handled that pretty well it seems. how would we port that functionality into elgg? also, how do we find out whether our own code is of use to minds.com?

**Comment by mrclay** [comment]
Both Minds and Elgg have branched off quite a bit in the last 3 years (at least) since this fork was begun. Supporting Cassandra, Neo4J, and whatever https://github.com/minds/sockets/ was (Node server I'm guessing?) would be steep new requirements for the many Elgg hobbyist users, and from what I can tell Minds is (smartly) working to clear away what remains of the old Elgg code to focus on the exact features they want and performance they need.

> how do we find out whether our own code is of use to minds.com

On a practical level they can simply diff code in classes and lib to see changes but so much refactoring has been done that this would be futile. It *would* be useful to know which Elgg version was forked initially so our team could study Mind's changes isolated.

**Comment by johnottman** [comment]
Minds worked with Elgg in our pre alpha versions. Our goal was massive scalability for rich content on commodity infrastructure. Minds today is heavily re engineered from the original Elgg footprint. New modules and features are end to end including blogs, video server, groups, encrypted messenger, video chat, boost, geo location and mobile app.
